# Generated by Django 4.1.2 on 2022-10-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=70, verbose_name='Фамилия')),
                ('age', models.IntegerField(verbose_name='Возраст студента')),
                ('gender', models.CharField(max_length=50, verbose_name='Пол студента')),
                ('course', models.CharField(max_length=50, verbose_name='Курс')),
            ],
        ),
    ]
